#!/bin/bash

CONFIG="$HOME/.config/rofi/config"
STYLE="$HOME/.config/rofi/style.css"
#COLORS="$HOME/.config/hypr/wofi/colors"

if [[ ! $(pidof wofi) ]]; then
	rofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} #--color ${COLORS}
else
	pkill rofi
fi
